drop table if exists users_roles;
drop table if exists students_groups;
drop table if exists students_courses;
drop table if exists course_groups;
drop table if exists teachers_students;
drop table if exists requested_students_courses;

drop table if exists lessons;
drop table if exists groups;
drop table if exists courses;
drop table if exists teachers;
drop table if exists students;
drop table if exists users;

create table users
(
    id        bigint generated by default as identity primary key,
    email     varchar(255) unique not null,
    username  varchar(255) unique not null,
    password  varchar(255)        not null,
    name      varchar(255)        not null,
    surname   varchar(255)        not null,
    phone     varchar(255)        not null,
    sex       varchar(255),
    user_role varchar(255)        not null
);

create table students
(
    id      bigint generated by default as identity primary key,
    user_id bigint,
    foreign key (user_id) references users (id)
);

create table teachers
(
    id            bigint generated by default as identity primary key,
    user_id       bigint,
    registered_at date not null,
    foreign key (user_id) references users (id)
);

create table courses
(
    id          bigint generated by default as identity primary key,
    name        varchar(255) unique not null,
    description text,
    teacher_id  bigint,
    literature  text,
    tasks       text,
    links       text,
    foreign key (teacher_id) references teachers (id)
);

create table groups
(
    id        bigint generated by default as identity primary key,
    name      varchar(255) not null,
    course_id bigint,
    foreign key (course_id) references courses (id)
);

create table lessons
(
    id               bigint generated by default as identity primary key,
    name             varchar(255) not null,
    description      text,
    duration_minutes int          not null,
    time_start       TIMESTAMP    not null,
    group_id         bigint,
    foreign key (group_id) references groups (id)
);

create table teachers_students
(
    student_id bigint,
    teacher_id bigint,
    primary key (student_id, teacher_id),
    foreign key (student_id) references students (id),
    foreign key (teacher_id) references teachers (id)
);

create table students_courses
(
    student_id bigint,
    course_id  bigint,
    primary key (student_id, course_id),
    foreign key (student_id) references students (id),
    foreign key (course_id) references courses (id)
);

create table requested_students_courses
(
    student_id bigint,
    course_id  bigint,
    primary key (student_id, course_id),
    foreign key (student_id) references students (id),
    foreign key (course_id) references courses (id)
);

create table students_groups
(
    student_id bigint,
    group_id   bigint,
    primary key (student_id, group_id),
    foreign key (student_id) references students (id),
    foreign key (group_id) references groups (id)
);

create table users_roles
(
    user_id bigint,
    roles   varchar(255),
    primary key (user_id, roles),
    foreign key (user_id) references users (id)
);
